-- Migration 034: Create metric_config table
-- Purpose: Ground truth for which metrics are active in reports
-- Generated: 2026-03-16
-- Dependencies: None

CREATE TABLE IF NOT EXISTS metric_config (
    metric_id    VARCHAR(50) PRIMARY KEY,
    status       VARCHAR(20) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    reason       TEXT,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by   VARCHAR(100),
    INDEX idx_status (status),
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO metric_config (metric_id, status, category, reason) VALUES
('uncertainty',     'deprecated', 'risk_metrics',       'Redundant with ATR+VWAP+VOL'),
('atr_pct',         'ready',      'risk_metrics',       NULL),
('vwap_pct',        'ready',      'risk_metrics',       NULL),
('volume_ratio',    'ready',      'risk_metrics',       NULL),
('current_price',   'ready',      'risk_metrics',       NULL),
('rsi',             'ready',      'momentum_indicators', NULL),
('macd',            'ready',      'momentum_indicators', NULL),
('macd_signal',     'ready',      'momentum_indicators', NULL),
('sma_20',          'ready',      'trend_indicators',    NULL),
('sma_50',          'ready',      'trend_indicators',    NULL),
('sma_200',         'ready',      'trend_indicators',    NULL),
('ema_12',          'ready',      'trend_indicators',    NULL),
('ema_26',          'ready',      'trend_indicators',    NULL),
('atr',             'ready',      'volatility_indicators', NULL),
('bollinger_upper', 'ready',      'volatility_indicators', NULL),
('bollinger_lower', 'ready',      'volatility_indicators', NULL),
('bollinger_middle','ready',      'volatility_indicators', NULL),
('vwap',            'ready',      'volume_indicators',   NULL),
('pe_ratio',        'ready',      'fundamentals',        NULL),
('eps',             'ready',      'fundamentals',        NULL),
('market_cap',      'ready',      'fundamentals',        NULL),
('revenue_growth',  'ready',      'fundamentals',        NULL),
('profit_margin',   'ready',      'fundamentals',        NULL),
('dividend_yield',  'ready',      'fundamentals',        NULL),
('roe',             'ready',      'fundamentals',        NULL),
('debt_to_equity',  'ready',      'fundamentals',        NULL),
('current_ratio',   'ready',      'fundamentals',        NULL),
('book_value',      'ready',      'fundamentals',        NULL),
('52_week_high',    'ready',      'fundamentals',        NULL),
('52_week_low',     'ready',      'fundamentals',        NULL),
('target_price',    'ready',      'fundamentals',        NULL),
('beta',            'ready',      'fundamentals',        NULL),
('performance_advantage', 'ready', 'comparative',        NULL),
('volatility_advantage',  'ready', 'comparative',        NULL),
('comparative_return',    'ready', 'comparative',        NULL),
('peer_count',            'ready', 'comparative',        NULL),
('strategy_buy_return',   'ready', 'strategy',           NULL),
('strategy_buy_sharpe',   'ready', 'strategy',           NULL),
('strategy_buy_win_rate', 'ready', 'strategy',           NULL),
('strategy_buy_drawdown', 'ready', 'strategy',           NULL),
('strategy_sell_return',  'ready', 'strategy',           NULL),
('strategy_sell_sharpe',  'ready', 'strategy',           NULL),
('strategy_sell_win_rate','ready', 'strategy',           NULL),
('strategy_sell_drawdown','ready', 'strategy',           NULL),
('uncertainty_percentile',      'deprecated', 'percentiles', 'Parent metric deprecated'),
('atr_pct_percentile',          'ready',      'percentiles', NULL),
('vwap_pct_percentile',         'ready',      'percentiles', NULL),
('volume_ratio_percentile',     'ready',      'percentiles', NULL),
('rsi_percentile',              'ready',      'percentiles', NULL),
('macd_percentile',             'ready',      'percentiles', NULL),
('macd_signal_percentile',      'ready',      'percentiles', NULL),
('sma_20_percentile',           'ready',      'percentiles', NULL),
('sma_50_percentile',           'ready',      'percentiles', NULL),
('sma_200_percentile',          'ready',      'percentiles', NULL),
('ema_12_percentile',           'ready',      'percentiles', NULL),
('ema_26_percentile',           'ready',      'percentiles', NULL),
('atr_percentile',              'ready',      'percentiles', NULL),
('bollinger_upper_percentile',  'ready',      'percentiles', NULL),
('bollinger_lower_percentile',  'ready',      'percentiles', NULL),
('bollinger_middle_percentile', 'ready',      'percentiles', NULL),
('vwap_percentile',             'ready',      'percentiles', NULL);
